name: tylercode-cycles
version: '0.8.0'
summary: A simple, theme-aware, CPU information tool
description: |
  This application displays all logical cores on the machine and the current clock speed and core utilization. The theme is controlled by the OS.
icon: snap/gui/icon.png

grade: stable
confinement: strict

base: core22

apps:
  tylercode-cycles:
    command: bin/cycles
    extensions: [gpu]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - home
      - wayland
      - unity7
      - pulseaudio

parts:
  tylercode-cycles:
    source: .
    plugin: go
    build-snaps:
      - go/1.21/stable
    build-packages:
      - libgl1-mesa-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxxf86vm-dev
      - libxi-dev
      - pkg-config
    stage-packages:
      - libx11-6
      - libxinerama1
      - libxcursor1
      - libxi6
      - libxrandr2
      - libxrender1
      - libasound2
      - libpulse0
