name: tylercode-cycles
version: '0.2'
summary: A simple, theme aware, cpu information tool
description: |
  This application displays all logical cores on the machine and the current clock speed and core utilization. The theme is controlled by the OS. 
icon: snap/gui/icon.png

grade: devel
confinement: classic

base: core18

apps:
  tylercode-cycles:
    command: bin/cycles

parts:
  tylercode-cycles:
    source: .
    plugin: go
    go-importpath: "github.com/TylerCode/cycles"
    build-packages:
      - libgl1-mesa-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - pkg-config
    stage-packages:
      - libgl1-mesa-glx
      - libx11-6
      - libxrandr2
      - libxinerama1
      - libxcursor1
      - libxi6
