name: Archive Repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Archive Repository
      run: |
        mkdir temp
        # Copy all files and directories except 'temp'
        shopt -s extglob
        cp -R !(temp) temp/
        tar -czf repo-archive.tar.gz temp

    - name: Upload Archive as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-archive
        path: repo-archive.tar.gz
