name: Archive Repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Archive Repository
      run: |
        mkdir temp
        cp -R * .github .gitignore temp/
        tar -czf repo-archive.tar.gz temp

    - name: Upload Archive as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: repo-archive
        path: repo-archive.tar.gz
